-- MOVED. This file is no longer the schema.
--
-- The database is now defined by the numbered migrations in
-- `supabase/migrations/`, applied in order:
--
--   0000_vaults.sql           the encrypted cloud vault (was this file, verbatim)
--   0001_social_identity.sql  accounts, handles, the directory
--   0002_social_graph.sql     mutual friendships
--   0003_social_binders.sql   published binders + the scope-driven read rule
--   0004_social_inbox.sql     trade proposals and replies
--
-- Why the change: this file was applied by hand in the SQL editor, so
-- `supabase_migrations.schema_migrations` was empty. The next person to run
-- `supabase link && supabase db push` would have had every migration replay
-- from zero against a database that already had the tables. The history is now
-- baselined on the live project (versions 0000-0004 recorded) and the
-- migrations are written idempotent-friendly, so a mistaken replay survives.
--
-- Read `docs/social.md` before changing any of it -- the read policies on
-- `binders` encode a privacy rule that is not obvious from the SQL alone.
